export const seenOnBway = [
    {
    id: 1,
    show: "The Lion King",
    showType: "Musical",
    theatre: "Minskoff",
    seenOn: "10/02/2008",
    stars: 5,
    },
    {
    id: 2,
    show: "Mary Poppins",
    showType: "Musical",
    theatre: "New Amsterdam",
    seenOn: "2009 approx.",
    stars: 5
    },
    {
    id: 3,
    show: "Phantom of the Opera",
    showType: "musical",
    theatre: "Majestic",
    seenOn: "2010 approx.",
    stars: 5,
    },
    {
    id: 4,
    show: "Peter and The Starcatcher",
    showType: "play",
    theatre: "Lena Horne",
    seenOn: "2012 approx.",
    stars: 5,
    },
    {
    id: 5,
    show: "Newsies",
    showType: "musical",
    theatre: "Nederlander",
    seenOn: "2013 approx.",
    stars: 4,
    },
    {
    id: 6,
    show: "Matilda",
    showType: "musical",
    theatre: "Sam S. Shubert",
    seenOn: "02/12/2014",
    stars: 3,
    },
    {
    id: 7,
    show: "Once",
    showType: "musical",
    theatre: "Bernard B. Jacobs",
    seenOn: "06/16/2014",
    stars: 3,
    },
    {
    id: 8,
    show: "The Lion King",
    showType: "musical",
    theatre: "Minskoff",
    seenOn: "04/30/2016",
    stars: 3.5,
    },
    {
    id: 9,
    show: "Wicked",
    showType: "musical",
    theatre: "Gershwin",
    seenOn: "06/01/2016",
    stars: 4.5,
    },
    {
    id: 10,
    show: "School of Rock: The Musical",
    showType: "musical",
    theatre: "Winter Garden",
    seenOn: "01/14/2018",
    stars: 3.5
    },
    {
    id: 11,
    show: "Spongebob Squarepants: The Broadway Musical",
    showType: "musical",
    theatre: "Palace",
    seenOn: "04/10/2018",
    stars: 5,
    },
    {
    id: 12,
    show: "Beautiful: The Carole King Musical",
    showType: "musical",
    theatre: "Stephen Sondheim",
    seenOn: "01/05/2019",
    stars: 4,  
    },
    {
    id: 13,
    show: "The Prom",
    showType: "musical",
    theatre: "Longacre",
    seenOn: "04/03/2019",
    stars: 4,
    },
    {
    id: 14,
    show: "Dear Evan Hansen",
    showType: "musical",
    theatre: "The Music Box",
    seenOn: "10/06/2019",
    stars: 4.5,
    },
    {
    id: 15,
    show: "Beetlejuice",
    showType: "musical",
    theatre: "Winter Garden",
    seenOn: "10/13/2019",
    stars: 3.5,   
    },
    {
    id: 16,
    show: "Frozen",
    showType: "musical",
    theatre: "St. James",
    seenOn: "01/12/2020",
    stars: 4,    
    },
    {
    id: 17,
    show: "Come From Away",
    showType: "musical",
    theatre: "Gerald Schoenfeld",
    seenOn: "03/08/2020",
    stars: 4.5,
    },
    {
    id: 18,
    show: "Freestyle Love Supreme",
    showType: "improv",
    theatre: "Booth",
    seenOn: "10/30/2021",
    stars: 4,    
    },
    {
    id: 19,
    show: "Freestyle Love Supreme",
    showType: "improv",
    theatre: "Booth",
    seenOn: "11/06/2021",
    stars: 5,    
    },
    {
    id: 20,
    show: "Girl from the North Country",
    showType: "musical",
    theatre: "Belasco",
    seenOn: "11/13/2021",
    stars: 2.5,
    },
    {
    id: 21,
    show: "Company",
    showType: "musical",
    theatre: "Bernard B. Jacobs",
    seenOn: "01/23/2022",
    stars: 5,
    },
    {
    id: 22,
    show: "Aladdin",
    showType: "musical",
    theatre: "New Amsterdam",
    seenOn: "01/30/2022",
    stars: 4.75,    
    },
    {
    id: 23,
    show: "MJ the Musical",
    showType: "musical",
    theatre: "Neil Simon",
    seenOn: "02/04/2022",
    stars: 4,
    },
    {
    id: 24,
    show: "Six the Musical",
    showType: "musical",
    theatre: "Lena Horne",
    seenOn: "05/22/2022",
    stars: 4.5,
    },
    {
    id: 25,
    show: "Dear Evan Hansen",
    showType: "musical",
    theatre: "The Music Box",
    seenOn: "07/22/2022",
    stars: 4.5,    
    },
    {
    id: 26,
    show: "Kimberly Akimbo",
    showType: "musical",
    theatre: "Booth",
    seenOn: "10/28/2022",
    stars: 4.25,
    },
    {
    id: 27,
    show: "Some Like It Hot",
    showType: "musical",
    theatre: "Sam S. Shubert",
    seenOn: "10/01/2023",
    stars: 4,
    },
    {
    id: 28,
    show: "Shucked",
    showType: "musical",
    theatre: "Nederlander",
    seenOn: "11/15/2023",
    stars: 3.5
    },
];

export const showTypes = [
    {value: "musical", label: "Musical"},
    {value: "play", label: "Play"},
    {value: "improv", label: "Improv Show"},
    {value: "concert", label: "Concert"},
    {value: "cabaret", label: "Cabaret Show"}
];

export const theatres = [
   {value: "Al Hirschfield", label: "Al Hirschfield Theatre"},
   {value: "Ambassador", label: "Ambassador Theatre"},
   {value: "August Wilson", label: "August Wilson Theatre"},
   {value: "Belasco", label: "Belasco Theatre"},
   {value: "Bernard B. Jacobs", label: "Bernard B. Jacobs Theatre"},
   {value: "Booth", label: "Booth Theatre"},
   {value: "Broadhurst", label: "Broadhurst Theatre"},
   {value: "Broadway", label: "Broadway Theatre"},
   {value: "Circle In The Square", label: "Circle in the Square Theatre"},
   {value: "Ethel Barrymore", label: "Ethel Barrymore Theatre"},
   {value: "Eugene O'Neill", label: "Eugene O'Neill Theatre"},
   {value: "Gerald Schoenfeld", label: "Gerald Schoenfeld Theatre"},
   {value: "Gershwin", label: "Gershwin Theatre"},
   {value: "Hayes", label: "Hayes Theatre"},
   {value: "Hudson", label: "Hudson Theatre"},
   {value: "Imperial", label: "Imperial Theatre"},
   {value: "James Earl Jones", label: "James Earl Jones Theatre"},
   {value: "John Golden", label: "John Golden Theatre"},
   {value: "Lena Horne", label: "Lena Horne Theatre"},
   {value: "Longacre", label: "Longacre Theatre"},
   {value: "Lunt-Fontanne", label: "Lunt-Fontanne Theatre"},
   {value: "Lyceum", label: "Lyceum Theatre"}, 
   {value: "Lyric", label: "Lyric Theatre"},
   {value: "Majestic", label: "Majestic Theatre"},
   {value: "Marquis", label: "Marquis Theatre"},
   {value: "Minskoff", label: "Minskoff Theatre"},
   {value: "The Music Box", label: "Music Box Theatre"},
   {value: "Nederlander", label: "Nederlander Theatre"},
   {value: "New Amsterdam", label: "New Amsterdam Theatre"},
   {value: "Palace", label: "Palace Theatre"},
   {value: "Richard Rogers", label: "Richard Rogers Theatre"},
   {value: "Samuel J. Friedman", label: "Samuel J. Friedman Theatre"},
   {value: "Shubert", label: "Shubert Theatre"},
   {value: "Stephen Sondheim", label: "Stephen Sondheim Theatre"},
   {value: "Studio 54", label: "Studio 54"},
   {value: "Todd Haimes", label: "Todd Haimes Theatre"},
   {value: "Vivian Beaumont", label: "Vivian Beaumont Theatre"},
   {value: "Walter Kerr", label: "Walter Kerr Theatre"},
   {value: "Winter Garden", label: "Winter Garden Theatre"}
];