import React from 'react';

class showRecord extends React.Component{
    showRecord = (Id, show, showType, theatre, seenOn, stars) => {
        this.Id = Id;
        this.show = show;
        this.showType = showType;
        this.theatre = theatre;
        this.seenOn = seenOn;
        this.stars = stars;
    }
};

export const seenOnBway = [
    {
    id: 1,
    show: "The Lion King",
    showType: "Musical",
    theatre: "Minskoff Theatre",
    seenOn: "10/02/2008",
    stars: 5,
    },
    {
    id: 2,
    show: "Mary Poppins",
    showType: "Musical",
    theatre: "New Amsterdam Theatre",
    seenOn: "2009 approx.",
    stars: "N/A"
    },
    {
    id: 3,
    show: "Phantom of the Opera",
    showType: "musical",
    theatre: "Majestic Theatre",
    seenOn: "2010 approx.",
    stars: "N/A",
    },
    {
    id: 4,
    show: "Peter and The Starcatcher",
    showType: "play",
    theatre: "Lena Horne Theatre (previously the Brooks Atkinson Theatre)",
    seenOn: "2012 approx.",
    stars: "5",
    },
    {
    id: 5,
    show: "Newsies",
    showType: "musical",
    theatre: "Nederlander Theatre",
    seenOn: "2013 approx.",
    stars: "4",
    },
    {
    id: 6,
    show: "Matilda",
    showType: "musical",
    theatre: "Sam S. Shubert Theatre",
    seenOn: "02/12/2014",
    stars: "3",
    },
    {
    id: 7,
    show: "Once",
    showType: "musical",
    theatre: "Bernard B. Jacobs Theatre",
    seenOn: "06/16/2014",
    stars: "3",
    },
    {
    id: 8,
    show: "The Lion King",
    showType: "musical",
    theatre: "Minskoff Theatre",
    seenOn: "04/30/2016",
    stars: "3.5",
    },
    {
    id: 9,
    show: "Wicked",
    showType: "musical",
    theatre: "Gershwin Theatre",
    seenOn: "06/01/2016",
    stars: "4.5",
    },
    {
    id: 10,
    show: "School of Rock: The Musical",
    showType: "musical",
    theatre: "Winter Garden Theatre",
    seenOn: "01/14/2018",
    stars: "3.5"
    },
    {
    id: 11,
    show: "Spongebob Squarepants: The Broadway Musical",
    showType: "musical",
    theatre: "Palace Theatre",
    seenOn: "04/10/2018",
    stars: "5",
    },
    {
    id: 12,
    show: "Beautiful: The Carole King Musical",
    showType: "musical",
    theatre: "Stephen Sondheim Theatre",
    seenOn: "01/05/2019",
    stars: "4",  
    },
    {
    id: 13,
    show: "The Prom",
    showType: "musical",
    theatre: "Longacre Theatre",
    seenOn: "04/03/2019",
    stars: "4",
    },
    {
    id: 14,
    show: "Dear Evan Hansen",
    showType: "musical",
    theatre: "The Music Box",
    seenOn: "10/06/2019",
    stars: "4.5",
    },
    {
    id: 15,
    show: "Beetlejuice",
    showType: "musical",
    theatre: "Winter Garden Theatre",
    seenOn: "10/13/2019",
    stars: "3.5",   
    },
    {
    id: 16,
    show: "Frozen",
    showType: "musical",
    theatre: "St. James Theatre",
    seenOn: "01/12/2020",
    stars: "4",    
    },
    {
    id: 17,
    show: "Come From Away",
    showType: "musical",
    theatre: "Gerald Schoenfeld Theatre",
    seenOn: "03/08/2020",
    stars: "4.5",
    },
    {
    id: 18,
    show: "Freestyle Love Supreme",
    showType: "improv",
    theatre: "Booth Theatre",
    seenOn: "10/30/2021",
    stars: "4",    
    },
    {
    id: 19,
    show: "Freestyle Love Supreme",
    showType: "improv",
    theatre: "Booth Theatre",
    seenOn: "11/06/2021",
    stars: "5",    
    },
    {
    id: 20,
    show: "Girl from the North Country",
    showType: "musical",
    theatre: "Belasco Theatre",
    seenOn: "11/13/2021",
    stars: "2.5",
    },
    {
    id: 21,
    show: "Company",
    showType: "musical",
    theatre: "Bernard B. Jacobs Theatre",
    seenOn: "01/23/2022",
    stars: "5",
    },
    {
    id: 22,
    show: "Aladdin",
    showType: "musical",
    theatre: "New Amsterdam Theatre",
    seenOn: "01/30/2022",
    stars: "4.75",    
    },
    {
    id: 23,
    show: "MJ the Musical",
    showType: "musical",
    theatre: "Neil Simon Theatre",
    seenOn: "02/04/2022",
    stars: "4",
    },
    {
    id: 24,
    show: "Six the Musical",
    showType: "musical",
    theatre: "Lena Horne Theatre (previously the Brooks Atkinson Theatre)",
    seenOn: "05/22/2022",
    stars: "4.5",
    },
    {
    id: 25,
    show: "Dear Evan Hansen",
    showType: "musical",
    theatre: "The Music Box",
    seenOn: "07/22/2022",
    stars: "4.5",    
    },
    {
    id: 26,
    show: "Kimberly Akimbo",
    showType: "musical",
    theatre: "Booth Theatre",
    seenOn: "10/28/2022",
    stars: "4.25",
    },
    {
    id: 27,
    show: "Some Like It Hot",
    showType: "musical",
    theatre: "Sam S. Shubert Theatre",
    seenOn: "10/01/2023",
    stars: "4",
    },
    {
    id: 28,
    show: "Shucked",
    showType: "musical",
    theatre: "Nederlander Theatre",
    seenOn: "11/15/2023",
    stars: "3.5"
    },
];

export const showTypes = [
    {value: "musical", label: "Musical"},
    {value: "play", label: "Play"},
    {value: "improv", label: "Improv Show"},
    {value: "concert", label: "Concert"},
    {value: "cabaret", label: "Cabaret Show"}
];

export const theatres = [
   {value: "AlHirschfield", label: "Al Hirschfield Theatre"},
   {value: "Ambassador", label: "Ambassador Theatre"},
   {value: "AugustWilson", label: "August Wilson Theatre"},
   {value: "Belasco", label: "Belasco Theatre"},
   {value: "BernardBJacobs", label: "Bernard B. Jacobs Theatre"},
   {value: "Booth", label: "Booth Theatre"},
   {value: "Broadhurst", label: "Broadhurst Theatre"},
   {value: "Broadway", label: "Broadway Theatre"},
   {value: "CircleInTheSquare", label: "Circle in the Square Theatre"},
   {value: "EthelBarrymore", label: "Ethel Barrymore Theatre"},
   {value: "EugeneONeill", label: "Eugene O'Neill Theatre"},
   {value: "GeraldSchoenfeld", label: "Gerald Schoenfeld Theatre"},
   {value: "Gershwin", label: "Gershwin Theatre"},
   {value: "Hayes", label: "Hayes Theatre"},
   {value: "Hudson", label: "Hudson Theatre"},
   {value: "Imperial", label: "Imperial Theatre"},
   {value: "JamesEarlJones", label: "James Earl Jones Theatre"},
   {value: "JohnGolden", label: "John Golden Theatre"},
   {value: "LenaHorne", label: "Lena Horne Theatre"},
   {value: "Longacre", label: "Longacre Theatre"},
   {value: "LuntFontanne", label: "Lunt-Fontanne Theatre"},
   {value: "Lyceum", label: "Lyceum Theatre"}, 
   {value: "Lyric", label: "Lyric Theatre"},
   {value: "Majestic", label: "Majestic Theatre"},
   {value: "Marquis", label: "Marquis Theatre"},
   {value: "Minskoff", label: "Minskoff Theatre"},
   {value: "MusicBox", label: "Music Box Theatre"},
   {value: "Nederlander", label: "Nederlander Theatre"},
   {value: "NewAmsterdam", label: "New Amsterdam Theatre"},
   {value: "Palace", label: "Palace Theatre"},
   {value: "RichardRogers", label: "Richard Rogers Theatre"},
   {value: "SamuelJFriedman", label: "Samuel J. Friedman Theatre"},
   {value: "Shubert", label: "Shubert Theatre"},
   {value: "StephenSondheim", label: "Stephen Sondheim Theatre"},
   {value: "Studio54", label: "Studio 54"},
   {value: "ToddHaimes", label: "Todd Haimes Theatre"},
   {value: "VivianBeaumont", label: "Vivian Beaumont Theatre"},
   {value: "WalterKerr", label: "Walter Kerr Theatre"},
   {value: "WinterGarden", label: "Winter Garden Theatre"}
];